#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Ron Shavit"
email = "me@ronshavit.com"

[ui]
default-command = "log"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
merge-editor = "diffconflicts"
diff-instructions = false

[[--scope]]
--when.commands = ["diff", "show"]

[merge]
hunk-level = "word"

[git]
push-new-bookmarks = false
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
write-change-id-header = true
track-default-bookmark-on-clone = true

[remotes.origin]
auto-track-bookmarks = 'ron/*'

[templates]
git_push_bookmark = '"ron/" ++ change_id.short()'
draft_commit_description = "builtin_draft_commit_description_with_diff"
commit_trailers = "format_signed_off_by_trailer(self)"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
  "-c",
  "let g:jj_diffconflicts_marker_length=$marker_length",
  "-c",
  "JJDiffConflicts!",
  "$output",
  "$base",
  "$left",
  "$right",
]
merge-tool-edits-conflict-markers = true

[commit]
verbose = true

[fsmonitor]
backend = "watchman"

[fsmonitor.watchman]
register-snapshot-trigger = true

[snapshot]
auto-update-stale = true

[aliases]
retrunk = ["rebase", "--skip-emptied", "-d", "trunk()"]
ret = ["retrunk"]
pullup = ['retrunk', '-s', 'mutable()']
d = ["diff"]
e = ["edit"]
n = ["new"]
gc = ["abandon", "-r", "empty() & mutable()"]
fetch = ["git", "fetch"]
push = ["git", "push"]
send-email = ["util", "exec", "--", "ron-jj-send-email"]
pr = ["util", "exec", "--", "ryu"]
